# Stingray BNO085 config
# See https://github.com/bnbhat/bno08x_ros2_driver
#     https://github.com/slgrobotics/bno08x_ros2_driver  (improved fork)
#     https://github.com/slgrobotics/robots_bringup/blob/main/Docs/Sensors/BNO085%20IMU.md
#
bno08x_driver:
  ros__parameters:

    frame_id: "imu_link"  # Match the existing frame_id

    # Communication Interface
    i2c:
      enabled: true
      bus: "/dev/i2c-1"
      address: "0x4A"

    publish:
      magnetic_field: 
        enabled: true
        rate: 100   # max 100 Hz
      imu:
        enabled: true
        rate: 100   # max 400 Hz
        orientation_yaw_variance: 0.005
