<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="battery_length" value="0.170"/>
    <xacro:property name="battery_width" value="0.050"/>
    <xacro:property name="battery_height" value="0.040"/>


    <joint name="battery_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="battery_link"/>
        <origin xyz="${chassis_length} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="battery_link">
        <visual>
            <origin xyz="0 0.05 0.01" rpy="0 0 0"/>
            <geometry>
                <box size="0.170 0.050 0.040"/>
            </geometry>
            <material name="black"/>
        </visual>

<!-- 
        <visual>
            <origin xyz="-0.011 0 -0.00" rpy="0 ${1.5} 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.02"/>
            </geometry>
            <material name="red"/>
        </visual>
 -->
    </link>

</robot>