<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <xacro:property name="depth_camera_offset_x" value="${chassis_length/2 - 0.06}"/>
    <xacro:property name="depth_camera_offset_z" value="0.58"/>

    <joint name="depth_camera_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="depth_camera_link"/>
        <origin xyz="${depth_camera_offset_x} 0 ${depth_camera_offset_z}" rpy="0 0 0"/>
    </joint>

    <link name="depth_camera_link">
        <visual>
            <geometry>
                <box size="0.010 0.03 0.03"/>
            </geometry>
            <material name="sensor_blue"/>
        </visual>
        <visual>
            <origin xyz="0 0 -0.05"/>
            <geometry>
                <cylinder radius="0.002" length="0.1"/>
            </geometry>
            <material name="sensor_blue"/>
        </visual>
    </link>

    <joint name="depth_camera_optical_joint" type="fixed">
        <!-- parent link="depth_camera_link"/ -->
        <parent link="chassis_link"/>
        <child link="depth_camera_link_optical"/>
        <!-- origin xyz="0 0 0" rpy="0 0 0"/ -->
        <origin xyz="${depth_camera_offset_x} 0 ${depth_camera_offset_z}" rpy="0 0 0"/>
    </joint>

    <link name="depth_camera_link_optical">
    </link>

    <!-- gz model -m dragger -s depth_camera -->
	  <gazebo reference="depth_camera_link">
        <sensor name='depth_camera' type='depth'>
          <pose>0 0 0 0 0 0</pose>
		      <always_on>true</always_on>
          <topic>gz_depth_camera</topic>
          <!-- future Gazebo versions might require "<frame_id>" here. Must reference an actual link in .xacro -->
          <!-- see <optical_frame_id> below     <gz_frame_id>depth_camera_link_optical</gz_frame_id> -->
          <update_rate>10</update_rate>
          <visualize>true</visualize>
          <enable_metrics>false</enable_metrics>
          <camera name='__default__'>
            <pose>0 0 0 0 0 0</pose>
            <horizontal_fov>1.047</horizontal_fov>
            <image>
              <width>320</width>
              <height>240</height>
              <!--format>RGB_INT8</format -->
              <format>B8G8R8</format>
              <anti_aliasing>4</anti_aliasing>
            </image>
            <camera_info_topic>gz_depth_camera_info</camera_info_topic>
            <trigger_topic></trigger_topic>
            <triggered>false</triggered>
            <clip>
              <near>0.1</near>
              <far>8</far>
            </clip>
            <save enabled='false'>
              <path>__default__</path>
            </save>
            <visibility_mask>4294967295</visibility_mask>
            <noise>
              <type>none</type>
              <mean>0</mean>
              <stddev>0</stddev>
            </noise>
            <distortion>
              <k1>0</k1>
              <k2>0</k2>
              <k3>0</k3>
              <p1>0</p1>
              <p2>0</p2>
              <center>0.5 0.5</center>
            </distortion>
            <lens>
              <type>stereographic</type>
              <scale_to_hfov>true</scale_to_hfov>
              <cutoff_angle>${pi/2}</cutoff_angle>
              <env_texture_size>256</env_texture_size>
            </lens>
            <optical_frame_id>depth_camera_link_optical</optical_frame_id>
          </camera>
        </sensor>
    </gazebo>

</robot>