<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="laser_offset_x" value="${chassis_length/4 + 0.05}"/>
    <xacro:property name="laser_offset_z" value="0.57"/>

    <!-- ********************* LIDAR SETUP *********************************  -->
    <!-- Each sensor must be attached to a link.                              -->

    <joint name="laser_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="laser_frame"/>
        <origin xyz="${laser_offset_x} 0 ${laser_offset_z}" rpy="0 0 0"/>
    </joint>

    <!-- the name "laser_frame" should correspond to /scan topic header->frame_id as defined in *.launch.py -->
    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="sensor_blue"/>
        </visual>
        <visual>
            <origin xyz="0 0 -0.05"/>
            <geometry>
                <cylinder radius="0.03" length="0.1"/>
            </geometry>
            <material name="sensor_blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- gz model -m dragger -s front_laser -->
    <gazebo reference="laser_frame">
        <!-- name must be "laser_frame", specifically for lasers. Must reference an actual link in .xacro -->
        <sensor name='laser_frame' type='gpu_lidar'>
          <pose>0 0 0 0 0 0</pose>
          <always_on>1</always_on>
          <!-- 6 Hz for LD14 - see "frequency" in dual_ekf_navsat_parameters.yaml -->
          <update_rate>6</update_rate>
          <topic>gz_scan</topic>
          <!-- future Gazebo versions might require "<frame_id>" here. Must reference an actual link in .xacro -->
          <gz_frame_id>laser_frame</gz_frame_id>
          <frame_id>laser_frame</frame_id>
          <ray>
            <scan>
              <horizontal>
                <samples>360</samples>
                <resolution>1</resolution>
                <min_angle>-${pi}</min_angle>
                <max_angle>${pi}</max_angle>
              </horizontal>
              <vertical>
                <samples>1</samples>
                <resolution>1</resolution>
                <min_angle>0.0</min_angle>
                <max_angle>0.0</max_angle>
              </vertical>
            </scan>
            <range>
              <min>0.3</min>
              <max>12.0</max>
              <resolution>0.01</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <mean>0</mean>
              <stddev>0.01</stddev>
            </noise>
          </ray>
          <visualize>true</visualize>
        </sensor>
    </gazebo>

</robot>