<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

	<!-- Values corrected for Dragger robot -->
    <xacro:property name="chassis_length" value="0.90"/>
    <xacro:property name="chassis_width" value="0.40"/>
    <xacro:property name="chassis_height" value="0.50"/>
    <xacro:property name="chassis_mass" value="30.0"/>
    <xacro:property name="wheel_radius" value="0.192"/>
    <xacro:property name="wheel_thickness" value="0.09"/>
    <xacro:property name="wheel_mass" value="1.0"/>
    <xacro:property name="wheel_offset_x" value="0.70"/>
    <xacro:property name="wheel_offset_y" value="0.290"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.12"/>
    <xacro:property name="caster_wheel_thickness" value="0.08"/>
    <xacro:property name="caster_wheel_mass" value="0.3"/>
    <xacro:property name="caster_wheel_offset_x" value="0.10"/>
    <xacro:property name="caster_wheel_offset_y" value="0.280"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
    <!-- Define the center of the main robot chassis projected on the ground -->   
    <link name="base_footprint">
    </link>
    
    <!-- ********************** ROBOT BASE *********************************  -->
    <link name="base_link">
    </link>
    
    <!-- The base footprint of the robot is located underneath the chassis -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis_link">
        <visual name="chassis_visual">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/4}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height/2}"/>
            </geometry>
            <material name="body_color"/>
        </visual>
        <visual name="chassis_top_visual">
            <origin xyz="${chassis_length*3/4} 0 ${chassis_height*3/4}"/>
            <geometry>
                <box size="${chassis_length*0.45} ${chassis_width*0.95} ${chassis_height/2}"/>
            </geometry>
            <material name="body_color"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- *********************** IMU SETUP *********************************  -->
    <!-- Each sensor must be attached to a link.                              -->

    <link name="imu_link">
        <visual>
        <geometry>
            <box size="0.1 0.1 0.1"/>
        </geometry>
        </visual>
        
        <collision>
        <geometry>
            <box size="0.1 0.1 0.1"/>
        </geometry>
        </collision>
    </link>
        
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0.01"/>
    </joint>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual name="left_wheel_visual">
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="port_red"/>
        </visual>
        <visual name="left_wheel_marker_visual">
            <geometry>
                <box size="${wheel_radius*0.5} ${wheel_radius*0.5} ${wheel_thickness*1.1}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <!-- visual name="left_wheel_marker_visual">
            <pose>0.17 0 0 0 0 0</pose>
            <geometry>
                <box size=".10 .01 .21"/>
            </geometry>
            <material>
                <ambient>1.0 0.2 0.2 1</ambient>
                <diffuse>1.0 0.1 0.1 1</diffuse>
                <specular>0 0 0 0</specular>
                <emissive>0 0 0 1</emissive>
            </material>
        </visual -->
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="starboard_green"/>
        </visual>
        <visual name="right_wheel_marker_visual">
            <geometry>
                <box size="${wheel_radius*0.5} ${wheel_radius*0.5} ${wheel_thickness*1.1}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CASTER WHEELS LINKS -->

    <joint name="left_caster_wheel_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="left_caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} ${caster_wheel_offset_y} ${caster_wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>


    <link name="left_caster_wheel">
        <visual>
            <geometry>
               <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_thickness}"/>
            </geometry>
            <material name="port_red"/>
        </visual>
        <visual name="left_caster_marker_visual">
            <geometry>
                <box size="${caster_wheel_radius*0.5} ${caster_wheel_radius*0.5} ${caster_wheel_thickness*1.1}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <joint name="right_caster_wheel_joint" type="continuous">
        <parent link="chassis_link"/>
        <child link="right_caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>


    <link name="right_caster_wheel">
        <visual>
            <geometry>
               <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_thickness}"/>
            </geometry>
            <material name="starboard_green"/>
        </visual>
        <visual name="left_caster_marker_visual">
            <geometry>
                <box size="${caster_wheel_radius*0.5} ${caster_wheel_radius*0.5} ${caster_wheel_thickness*1.1}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <!-- gazebo reference="right_caster_wheel">
        <material>Gazebo/Green</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="left_caster_wheel">
        <material>Gazebo/Red</material>
        <material>
            <ambient>1.0 0.2 0.2 1</ambient>
            <diffuse>1.0 0.1 0.1 1</diffuse>
        </material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="right_wheel">
        <material>Gazebo/Green</material>
    </gazebo -->

</robot>