controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    # Base frame_id, which is used to fill in the child_frame_id of the Odometry messages and TF. Default: base_link
    #base_frame_id: base_link
    base_frame_id: base_footprint

    # See http://wiki.ros.org/diff_drive_controller

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.600
    wheel_radius: 0.185

    use_stamped_vel: false

    # open_loop: false    

    wheels_per_side: 1
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # Name of frame to publish odometry in. Default: "/odom"
    odom_frame_id: '/odom'

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # open_loop: x

    # Publish to TF directly or not. Default: true
    enable_odom_tf: true

    cmd_vel_timeout: 1.0
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    #linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    #linear.x.max_velocity: 0.320    # m/s - experimental on actual robot
    #linear.x.min_velocity: -0.320
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    #angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    #angular.z.max_velocity: 0.185    # rad/s - experimental on actual robot
    #angular.z.min_velocity: -0.185
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN


# joint_broad:
#   ros__parameters: