<?xml version="1.0" encoding="UTF-8"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:macro name="create_wheel" params="prefix y_offset wheel_radius wheel_width">
    <link name="${prefix}_wheel_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <!-- joint name="${prefix}_wheel_joint" type="fixed" -->
    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="0 ${y_offset} ${-wheel_radius}" rpy="0 0 0"/>
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel_link"/>
      <axis xyz="0 1 0"/>
    </joint>

  </xacro:macro>

  <xacro:macro name="create_base" 
               params="diffdrive_update_rate:=40 wheel_separation wheel_radius:=0.033 wheel_width:=0.024 wheel_torque:=1.0 wheel_accel:=1.8 mass_kg:=3.5 base_diameter *mesh">

    <!-- replaced with ros2_control.xacro -->
    <!-- xacro:include filename="$(find articubot_one)/robots/turtle/description/create_base_gazebo.urdf.xacro"/ -->

    <!-- The coordinate frame called base_link is rigidly attached to the robot root body. -->
    <link name="base_link">
      <visual name="baselink_visual">
          <origin xyz="0 0 0"/>
          <geometry>
              <sphere radius="0.01"/>
          </geometry>
          <material name="red"/>
      </visual>
    </link>

    <!-- Define the center of the main robot chassis projected on the ground -->   
    <link name="base_footprint">
      <visual name="footprint_visual">
          <origin xyz="0 0 0"/>
          <geometry>
              <cylinder radius="${base_diameter/2 + 0.01}" length="0.003"/>
          </geometry>
          <material name="shadow_grey"/>
      </visual>
    </link>

    <!-- The base footprint of the robot is located underneath the chassis -->
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint" />
      <origin xyz="0 0 -${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
      <parent link="base_link"/>
      <child link="chassis_link"/>
      <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <!-- CHASSIS LINK -->
    <link name="chassis_link">
      <inertial>
        <mass value="${mass_kg}"/>
        <origin xyz="0 0 0.0"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.5"/>
      </inertial>
      <visual>
        <origin xyz=" 0 0 -0.015" rpy="0 0 0"/>
        <geometry>
          <xacro:insert_block name="mesh"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.0611632" radius="${base_diameter/2}"/>
        </geometry>
      </collision>
    </link>

    <link name="wall_sensor_link">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <link name="left_cliff_sensor_link">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <link name="right_cliff_sensor_link">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <link name="leftfront_cliff_sensor_link">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>

    <link name="rightfront_cliff_sensor_link">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="base_wall_sensor_joint" type="fixed">
      <origin xyz="0.09 -0.120 0.042" rpy="0 0 -1.0"/>
      <parent link="chassis_link"/>
      <child link="wall_sensor_link"/>
    </joint>
    <joint name="base_left_cliff_sensor_joint" type="fixed">
      <origin xyz="0.07 0.14 0.01" rpy="0 ${PI/2} 0"/>
      <parent link="chassis_link"/>
      <child link="left_cliff_sensor_link"/>
    </joint>
    <joint name="base_right_cliff_sensor_joint" type="fixed">
      <origin xyz="0.07 -0.14 0.01" rpy="0 ${PI/2} 0"/>
      <parent link="chassis_link"/>
      <child link="right_cliff_sensor_link"/>
    </joint>
    <joint name="base_leftfront_cliff_sensor_joint" type="fixed">
      <origin xyz="0.15 0.04 0.01" rpy="0 ${PI/2} 0"/>
      <parent link="chassis_link"/>
      <child link="leftfront_cliff_sensor_link"/>
    </joint>
    <joint name="base_rightfront_cliff_sensor_joint" type="fixed">
      <origin xyz="0.15 -0.04 0.01" rpy="0 ${PI/2} 0"/>
      <parent link="chassis_link"/>
      <child link="rightfront_cliff_sensor_link"/>
    </joint>

    <xacro:create_wheel prefix="left" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:create_wheel prefix="right" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>

    <link name="front_castor_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <geometry>
          <sphere radius="0.018"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <geometry>
          <sphere radius="0.018"/>
        </geometry>
      </collision>
    </link>

    <!-- fixed because there's no transmission -->
    <joint name="front_castor_joint" type="fixed">
      <origin xyz="0.13 0 -0.048" rpy="0 0 0"/>
      <parent link="chassis_link"/>
      <child link="front_castor_link"/>
      <axis xyz="0 1 0"/>
    </joint>

    <joint name="imu_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="imu_link"/>
      <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
    </joint>

    <link name="imu_link"/>

    <joint name="scan_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="laser_frame"/>
      <origin xyz="0.085 0 0.033" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
      <visual>
        <geometry>
          <cylinder radius="0.0375" length="0.025"/>
        </geometry>
        <material name="sensor_blue"/>
      </visual>
      <visual>
        <origin xyz="0 0 -0.01"/>
        <geometry>
          <cylinder radius="0.01" length="0.02"/>
        </geometry>
        <material name="sensor_blue"/>
      </visual>
    </link>

  </xacro:macro>

</robot>
